### ISSUE TITLE
need add goneAwayExceptions

### ISSUE THREAD

**Issue by bryantyan** [facile-it/doctrine-mysql-come-back#23]
[2017-10-23 11:49:49] lumen.DEBUG: An exception occurred while executing 'SELECT t0.operator_id AS operator_id_1, t0.company_id AS company_id_2, t0.bind_status AS bind_status_3, t0.is_companyadmin AS is_companyadmin_4, t0.deleted_at AS deleted_at_5 FROM operator_bind_company t0 WHERE t0.operator_id = ? LIMIT 1' with params ["1"]:

Error while sending QUERY packet. PID=824

[2017-10-23 11:49:49] lumen.ERROR: ErrorException: Error while sending QUERY packet. PID=824 in /srv/www/espier-bloated/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105
Stack trace:
#0 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(2, 'Error while sen...', '/srv/www/espier...', 105, Array)
#1 /srv/www/espier-bloated/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(105): PDOStatement->execute(NULL)
#2 /srv/www/espier-bloated/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(907): Doctrine\DBAL\Driver\PDOStatement->execute()

[2017-10-23 11:50:08] lumen.DEBUG: An exception occurred while executing 'SELECT t0.operator_id AS operator_id_1, t0.company_id AS company_id_2, t0.bind_status AS bind_status_3, t0.is_companyadmin AS is_companyadmin_4, t0.deleted_at AS deleted_at_5 FROM operator_bind_company t0 WHERE t0.operator_id = ? LIMIT 1' with params ["1"]:

SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

**Comment by Jean85** [comment]
I'm sorry, can you clarify your request? Are you using this package with Lumen and it doesn't seem to work? Have you tried debugging the issue further?

**Comment by bryantyan** [comment]
I'm using lumen + laravel-doctrine + doctrine-mysql-come-back

the problem is when i using task consumer, ``` /srv/www/espier-bloated/artisan queue:work --queue=slow --delay=3 --memory=128 --timeout=1800 --sleep=1 --tries=3```


After that things got running more smoothly and it took a while before we encountered new problems. While spitting trough the logs I notices some consumers produced some errors. A brief summary:

- General error: 2006 MySQL server has gone away
- Error while sending QUERY packet.

Because the consumer is one process that keeps running, that also means that the service container and stuff keeps existing in memory. When you’ve done some queries the database connection keeps open in the background. And if it’s quiet on our queue, it may take some time before we reach the message limit. If that time exceeds the ```wait_connect``` of your MySQL server, you’ll run into the warnings and errors about lost connections.

so I can modify file ```ServerGoneAwayExceptionsAwareTrait``` solve this problem
```
trait ServerGoneAwayExceptionsAwareTrait
{
    /** @var string[] */
    protected $goneAwayExceptions = [
        'MySQL server has gone away',
        'Lost connection to MySQL server during query',
        'Error while sending QUERY packet',  #add
    ];

    /** @var string[] */
    protected $goneAwayInUpdateExceptions = [
        'MySQL server has gone away',
        'Error while sending QUERY packet', # add
    ];
```
but bring a new problem,  throw ```Error while sending QUERY packet``` have other reason

**Comment by Jean85** [comment]
Does that first exception have a previous exception attached? Maybe we can inspect that to find the right one, the one with the `MySQL server has gone away` message...

**Comment by samuelnogueira** [comment]
As far as I could test this, in the previous exception attached there isn't any `MySQL server has gone away` message since it is an error and not a PDO exception:
![image](https://user-images.githubusercontent.com/12846646/38803475-43c00b54-4167-11e8-953b-dd466e126ee6.png)

The `"Error while sending QUERY packet"` might occur in other situations other than server/client timeout, such as the query being too big, so handling these errors as gone away errors doesn't seem like a solution.

I don't have any ideia on how to fix this, does it help if I supply a test case to reproduce this?

**Comment by Jean85** [comment]
If the error is not a PDO exception, I think it could be out of scope fixing this here. I would suggest you to find an other solution, like extending this lib to solve your problem.

**Comment by samuelnogueira** [comment]
Also, seems to be happening with MariaDB at latest version, not with MySQL.
For posterity, it can be reproduced via docker-compose with these 3 files:

**test.php**
```php
<?php
$pdo = new PDO('mysql:host=db', 'root');
sleep(2);
$pdo->query('SELECT 1');
```

**docker-compose.yml**
```yaml
version: '3'
services:
  php:
    build: ./
    volumes:
      - ./:/app/
  db:
    image: mariadb:10.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    command:
      --wait-timeout=1
```

**Dockerfile**
```Dockerfile
FROM php:7.2

RUN docker-php-ext-install pdo_mysql
RUN echo 'error_reporting = E_ALL' > /usr/local/etc/php/php.ini

WORKDIR /app
```

And these commands:
```sh
docker-compose up -d
docker-compose run --rm php php test.php
```

Nevertheless, I agree this is outside the scope of this library, it seems kind of a PDO quirk that should be fixed in PDO itself.
